function h = parabolicHeight(pp, i, d)
  h = (pp.q(i) + d) / pp.n(i + 1) - pp.n(i - 1) * ...
  ((pp.n(i) - pp.n(i - 1) + d) * ...
   (pp.q(i + 1) - pp.q(i)) / (pp.n(i + 1) - pp.n(i)) + ...
   (pp.n(i + 1) - pp.n(i) - d) * ...
   (pp.q(i) - pp.q(i - 1)) / ...
   (pp.n(i) - pp.n(i - 1)));
end
